version: '2'
services:
  nginx:
    image: wlyg/nginx
    container_name: nginx
    working_dir: /srv
    restart: always
    ports:
      - 80:80
      - 443:443
    expose:
      - 80
      - 443
    depends_on:
      - mongo
      - redis
      - php
    links:
      - mongo:mongo
      - redis:redis
      - php:php
    volumes:
      - ../frontend/:/srv/frontend/:rw
      - ../backend/:/srv/backend/:rw
      - ./nginx/conf/:/etc/nginx/conf.d/:rw
      - ./nginx/ssl/:/etc/nginx/ssl/:rw
    networks:
      - backend

  php:
    image: wlyg/php
    container_name: php
    working_dir: /srv
    restart: always
    ports:
      - 9000:9000
    depends_on:
      - mongo
      - redis
    links:
      - mongo:mongo
      - redis:redis
    volumes:
      - ../frontend/:/srv/frontend/:rw
      - ../backend/:/srv/backend/:rw
    networks:
      - backend

  mongo:
    image: wlyg/mongo
    container_name: mongo
    restart: always
    ports:
      - 27017:27017
    expose:
      - 27017
    volumes:
      - ./mongodb/data:/data/db:rw
    networks:
      - backend

  redis:
    image: wlyg/redis
    container_name: redis
    restart: always
    ports:
      - 6379:6379
    expose:
      - 6379
    volumes:
      - ./redis/data:/data:rw
    networks:
      - backend

networks:
  backend:
    driver: bridge
